### ISSUE TITLE
Make typographical conventions consistent

### ISSUE THREAD

**Issue by basilleaf** [SETI/pds-opus#165]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

a couple of typographical conventions are at play, make them consistent, such as: 
- sometimes title case is used where other times all lower case is used 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/165

**Comment by rfrenchseti** [comment]
Duplicate of #264
