### ISSUE TITLE
Support cyclic latitude

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/pds-opus#452]
Right now we support cyclic longitude and RA, but just use normal ranges for latitude and DEC. We should support cyclic constraints in those cases too.

**Comment by markshowalter** [comment]
Nope. Dec and latitude are only -90 to 90.

On Aug 30, 2018, at 5:21 PM, Robert French <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now we support cyclic longitude and RA, but just use normal ranges for latitude and DEC. We should support cyclic constraints in those cases too.

**Comment by rfrenchseti** [comment]
Duh. Never mind. It's not that they are only -90 to 90, it's that latitude doesn't wrap around...

________________________________
